### ISSUE TITLE
Is it possible to add supports with IR fan, IR light etc.?

### ISSUE THREAD

**Issue by tsunglung** [ryanh7/SmartAC#2]
Is it possible to add supports with IR fan, IR light etc.?

**Comment by ryanh7** [comment]
我猜你会中文，并且这个插件的大部分使用者都会中文，所以我用中文回复你。红外风扇、红外灯之类的设备控制信号比较简单，且类型很多，这个插件使用的数据库无法保证有效覆盖这些设备。因此建议可以考虑使用其他已有的插件，比如smartir之类的。
