### ISSUE TITLE
请问红外码库Codes文件夹在哪里下载

### ISSUE THREAD

**Issue by liqingboyou** [ryanh7/SmartAC#4]
直接安装到HA后无法使用，应该是缺少码库，请问红外码库Codes文件夹在哪里下载

**Comment by chen-xiaobo** [comment]
> 

https://bbs.hassbian.com/thread-15867-1-1.html

**Comment by ryanh7** [comment]
支持irext项目的码库文件，考虑到潜在的许可问题，具体码库文件不包含在本项目中。
