### ISSUE TITLE
缺少空调索引文件

### ISSUE THREAD

**Issue by daixs** [ryanh7/SmartAC#6]
空调索引文件 那边下载有啊？

**Comment by Uniquemf** [comment]
从 https://cc.irext.net/code/ 下载对应的编码, index.json格式如下,将下载的遥控编码bin文件和写好的index.json一起放入custom_components/smartac/codes文件夹,重新安装集成即可显示
```
[
    {
        "brand_name": "Meida",
        "devices": [
            {
                "device_name": "new_ac_3387",
                "bin": "irda_new_ac_3387.bin"
            }
        ]
]

**Comment by pat28229** [comment]
> 

非常感谢

**Comment by pat28229** [comment]
> 从 https://cc.irext.net/code/ 下载对应的编码, index.json格式如下,将下载的遥控编码bin文件和写好的index.json一起放入custom_components/smartac/codes文件夹,重新安装集成即可显示
> 
> ```
> [
>     {
>         "brand_name": "Meida",
>         "devices": [
>             {
>                 "device_name": "new_ac_3387",
>                 "bin": "irda_new_ac_3387.bin"
>             }
>         ]
> ]
> ```

这个代码是否正确，他提示空调索引文件有问题

**Comment by Uniquemf** [comment]
https://github.com/Uniquemf/SmartAC/blob/master/custom_components/smartac/codes/index.json

**Comment by xujiaqing2016** [comment]
> 从 https://cc.irext.net/code/ 下载对应的编码, index.json格式如下,将下载的遥控编码bin文件和写好的index.json一起放入custom_components/smartac/codes文件夹,重新安装集成即可显示
> 
> ```
> [
>     {
>         "brand_name": "Meida",
>         "devices": [
>             {
>                 "device_name": "new_ac_3387",
>                 "bin": "irda_new_ac_3387.bin"
>             }
>         ]
> ]
> ```

这个网址是不是下架挂掉了？

**Comment by ryanh7** [comment]
索引文件及readme已更新
